language: node_js
node_js:
  - "8"
dist: trusty
sudo: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/
  committer-from-gh: true
  on:
    branch: master
